<center><img src="img/numpy_logo.png"></center>

<h1>NumPy (Numerical Python)</h1>
<p><em><b>Manual de Referencia NumPy:</b> <a href="https://numpy.org/doc/stable/numpy-ref.pdf">https://numpy.org/doc/stable/numpy-ref.pdf</a></em></p>
<p>Es una librería de Python que provee una serie de métodos para realizar operaciones matemáticas sobre una estructura de datos en forma de matriz (llamado <b>array</b>), que puede ser uni-dimensional (arreglo), bi-dimensional (matriz) o n-dimensional (tensores).</p>
<center><img src="img/numpy1.png"></center>
<p>Un array NumPy es un paquete de matrices N-dimensional que tienen forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria.</p>


<h3>Instalación</h3>
<p>Al trabajar en un entorno local, debemos instalar el paquete NumPy. <b>Recordá crear un entorno virtual previamente.</b> Si estamos trabajando en entornos tipo notebook, no necesitamos instalar ningún paquete para trabajo con datos (NumPy, PanDas, Matplotlib, etc.), sólo necesitamos importarlos.</p>
<center><img src="img/instala_numpy.png"></center>

<h3>Importando la librería</h3>
<center><img src="img/importar_numpy.png"></center>

In [1]:
import numpy as np

#USOS BÁSICOS

lista_nros = [12,12,14,15,16,16,16,20,2,3,4,5,5,7,8,10,22,22]
print( lista_nros )
print( type(lista_nros))
'''
Para poder manipular mi lista python con numpy, necesito convertirla en un ARREGLO o 
VECTOR
Voy a usar el método array() de numpy y le voy a pasar como parámetro la lista
Como le puse un alias a mi numpy importado (np), lo voy a usar para invocar a 
este método de ahora en adelante
'''

#creamos un array con la lista de num "lista_nros" :
array_nros = np.array(lista_nros)
print(array_nros)

#vemos que tipos de datos son:
print(type(lista_nros))
print(type( array_nros ))

#observamos que los elementos del arreglo -array- se separan por espacios
#en cambio los elementos de la lista se separan por comas


[12, 12, 14, 15, 16, 16, 16, 20, 2, 3, 4, 5, 5, 7, 8, 10, 22, 22]
<class 'list'>
[12 12 14 15 16 16 16 20  2  3  4  5  5  7  8 10 22 22]
<class 'list'>
<class 'numpy.ndarray'>


In [2]:
# Cuando utilizamos los siguientes metodos se ordenan automaticamente
# No es necesario ordenarlos antes de aplicar cada uno.

<h3>Medidas de tendencia central en NumPy</h3>

In [3]:
# MEDIA 

# Es el porcentaje de todos los valores de nuestro array o matriz

array_nros = np.array([5,5,5,7,8,10,12,12,14,15,16,16,16,20,2,2,2,3,4,22,22])
media = np.mean(array_nros)

print("Promedio/Media:" , f"{media:.2f}")

#cuando ingresamos " :.2f " nos indica que solo tomara DOS DECIMALES.


Promedio/Media: 10.38


In [4]:
# MEDIANA 

# En el valor que se encuantra en el centro en cuanto a posicion
# Si hay dos valores en el medio, se toma un porcertaje de los dos.

mediana = np.median(array_nros)
print("La mediana es: " , mediana)

La mediana es:  10.0


In [5]:
# CUARTILES

# son tres valores que nos dividen el dataset en cuatro partes
# 0.25 - 0.50 - 0.75  --> 0.50 es la mitad por eso igual a la mediana
# metodo quantile(arreglo , quantile)

q1 = np.quantile(array_nros , 0.25)
q2 = mediana
q3 = np.quantile(array_nros , 0.75)

print(f"Q1 = {q1} , Q2 = {q2} , Q3 = {q3}")

Q1 = 5.0 , Q2 = 10.0 , Q3 = 16.0


In [6]:
# PERCENTIL 

#Es una medida de dispersión parecida a los cuartiles. Es más especifico
# divide la muestra (dataset) en 100 partes --> trabaja con porcentajes
# método percentile(arreglo, cuántos elementos tomar)

p60 = np.percentile(array_nros , 60)
p20 = np.percentile(array_nros , 20)
p50 = np.percentile( array_nros , 50)

print("Percentil 60:" , p60)
print("Percentil 20:" , p20)
print("Percentil 50:" , p50)

Percentil 60: 12.0
Percentil 20: 4.0
Percentil 50: 10.0


In [7]:
''' MODA
me devuelve un objeto de tipo ModeResult(array_con_el_primer_valor_que_encuentra, 
recuento_de_apariciones)
Sólo devuelve la primera ocurrencia en un vector ORDENADO si hay más valores, 
los ignora '''

# son todos módulos de numpy, excepto mode()

' MODA\nme devuelve un objeto de tipo ModeResult(array_con_el_primer_valor_que_encuentra, \nrecuento_de_apariciones)\nSólo devuelve la primera ocurrencia en un vector ORDENADO si hay más valores, \nlos ignora '

In [8]:
# Varianza 


In [9]:
# Desvío Standard

<h3>Creando estructuras de datos con NumPy</h3>

Los arreglos en Numpy tienen que tener <b>sí o sí</b> los mismos tipos de datos -> los diferencia de las listas Py.

A los elementos de un vector se accede como a lo de los iterables conocidos -> con índice.

Les puedo aplicar slicing.

In [10]:
# CREAR ARREGLOS = ARRAY = VECTOR -> 1 fila, n columnas
# MATRIZ UNIDIMENSIONAL


lista_numeros = [1,100,3,66,23,11]

arr = np.array(lista_numeros)

print("Primer elemento:" , type(arr[0]))
print("Ultimo elemento:" , arr[-1])

# En la lista son solo números
# Si encuentra un string -texto- lo convierte en 'str' a la lista
# Es una COHERSION de datos

# El último número es [-1] y también [6] en este caso
#El anteúltimo correspondería a [-2] y también [5]

Primer elemento: <class 'numpy.int64'>
Ultimo elemento: 11


In [11]:
# CREAMOS UNA MATRIZ = ARREGLO BI-DIMENSIONAL

# Una lista de lista es una matriz:
lista_numeros = [ [1,10,9] , [2,5,2] ]
print("Lista Py:" , lista_numeros)
print()

arr_numeros = np.array( lista_numeros )
print("Arreglo NumPy")
print( arr_numeros )
print()

#Accediendo a los valores en un matriz--->[fila,columna] o [row,column]
print(arr_numeros[0,1])
print(arr_numeros[1,2])


Lista Py: [[1, 10, 9], [2, 5, 2]]

Arreglo NumPy
[[ 1 10  9]
 [ 2  5  2]]

10
2


<h4>ACTIVIDAD</h4>
<ul><li>Crear dos listas con datos de tipo homogéneo.</li>
<li>Una de las listas -> convertirla a vector</li>
<li>La otra -> convertirla a una matriz de 3 filas x 4 columnas</li></ul>

In [12]:
lista_uno = ["Frutilla" ,"Pedro" , "Rojo" , "Azul"]  #lista de string
lista_dos = [ [3,4,5,6] , [7,8,9,10] , [11,12,13,14]] #lista de num

arr_uno = np.array(lista_uno) #vector
arr_dos = np.array(lista_dos) #matriz de 3x4

print(arr_uno)
print(arr_dos)

['Frutilla' 'Pedro' 'Rojo' 'Azul']
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


<h3>Forzando el tipo de dato</h3>

In [13]:
#forzar a que se convierta en flotante:
array1 = np.array([[1.5,2,3,4],[5,6,7,8]] , dtype=np.float64) 
print(array1)

#forzar a que se convierta en entero:
array2 = np.array([[1.5,2,3,4],[5,6,7,8]] , dtype=np.int64) 
print(array2)

# Si el dato es convertible no voy a tener ningun tipo de problema



[[1.5 2.  3.  4. ]
 [5.  6.  7.  8. ]]
[[1 2 3 4]
 [5 6 7 8]]


<h3>Arreglos vacíos</h3>
<p>A veces se crean arreglos vacíos, para luego ser rellenados.</p>
<p>Se inicializan con unos, ceros, valores espaciados uniformemente, valores constantes o valores aleatorios. </p>

In [14]:
# arreglo de unos 
unos_a = np.ones(3)
print(unos_a)
print()

unos_b = np.ones((3,5))
print(unos_b)
print()

unos_c = np.ones((3,5) , dtype=np.int64)
print(unos_c)

[1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
# arreglo de ceros
cero = np.zeros(3)
print(cero)

print()

cero_b = np.zeros((5,5))
print(cero_b)

[0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# arreglo de nros aleatorios 
nros = np.random.random(3)
print( nros )
print()

nros_b = np.random.random((3,5))
print(nros_b)
print()


nros_c = np.random.randint(1,10,5)  # 5 num random entre 1 y 10
print(nros_c)

print()

nros_d = np.random.randint(1,100,(5,5))  # matriz 5X5 de num random
print( nros_d)

# 'Random' es una metodo que a su vez tiene múltiples métodos
# random.random me devuelve valores aleatorios entre 0 y 1.
# random.randint me devuelve numeros enteros aleatorios ,
# NO toma el valor donde termina el rango -valor final- (en este caso 100)
# np.random.randint(num_min , num_max , cantidad_num)

[0.12531707 0.09166919 0.09295227]

[[0.90077221 0.51028568 0.75663658 0.12205669 0.6684155 ]
 [0.59008664 0.15651709 0.83470702 0.72338767 0.60671344]
 [0.40968186 0.21557826 0.67588871 0.56097741 0.86598563]]

[7 4 5 1 3]

[[64 18  6 25 53]
 [86 28 78 14  7]
 [11 72 36 30 97]
 [33 47 63 58 71]
 [75 23 75 44 47]]


In [17]:
# llena todo el arreglo con el mismo valor
nueves = np.full((2,3), 9)
print( nueves )

#crea una matriz con un valor que determinamos,en este caso 9
# np.full((row,column), num)

[[9 9 9]
 [9 9 9]]


Para crear arreglos con valores espaciados uniformemente podemos utilizar np.arange() y np.linspace()


In [18]:
# np.arange(): deseo crear un arreglo con los valores comprendidos entre 0 y 100 a paso 5
# nos da un arreglo entre determinados numeros que saltan, en este caso 5
# np.arange=(num_min , num_max , valor_salto)

arr_uno = np.arange(0, 101, 5)
print( arr_uno )



# np.linspace(): deseo crear 5 valores que se encuentren entre 0 y 2
# nos da un arreglo entre determinados numeros con la cantidad indicada
# np_linspace(num_min , num_max , cantidad_valores)

arr_dos = np.linspace(0, 2, 5)
print( arr_dos )




 
# np.linspace(min, max, n) me divide el rango en min-max en n partes y llena el arreglo con los valores que me da la división

 

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
[0.  0.5 1.  1.5 2. ]


<h3>Matriz identidad</h3>

In [19]:
matriz_identidad = np.eye(4)
print(matriz_identidad)
print()

mt = np.identity(4, dtype=np.int64)
print(mt)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


<h3>Inspeccionar arreglos</h3>


In [20]:

arreglo = np.array([(1, 3, 5, 7), (9.5, 3, 4, 5), (1, 1, 1, 1)])  # es una lista de tuplas

print(arreglo)
print(arreglo.dtype)  # devuelve el tipo de dato
print(arreglo.shape)  # devuelve el formato fila-columna
print(arreglo.size)  # devuelve la cantidad de datos




[[1.  3.  5.  7. ]
 [9.5 3.  4.  5. ]
 [1.  1.  1.  1. ]]
float64
(3, 4)
12


<h3>Cambio de tamaño y forma</h3>

In [21]:
matriz = np.array([(8, 9, 10) , (11, 12, 13)])  #lista de tuplas
print(matriz)

print()

matriz_b = matriz.reshape(3,2)
print(matriz_b)

# matriz.reshape(filas,columnas) nos cambia las filas-columans del arreglo
# reshape NO modifica el original, devuelve una COPIA.
# paso de ser un arreglo de 2 filas y 3 columnas, a ser de 3 filas y 2 columnas
# se puede cambiarel formato siempre y cuando seaposible redimensionar
# si la cantidad de elementos alcanza o son factibles no hay problema.

[[ 8  9 10]
 [11 12 13]]

[[ 8  9]
 [10 11]
 [12 13]]


<h3>Operaciones matemáticas</h3>

In [22]:
arr_a = np.arange(4)
print(arr_a)

print(arr_a + 5)
# se le suma 5 numeros a CADA uno de los elementos del arreglo

print(arr_a * 2)
# multiplica por dos a CADA uno de los elementos del arreglo

[0 1 2 3]
[5 6 7 8]
[0 2 4 6]


<h3>Universal functions (ufunc)</h3>
https://www.w3schools.com/python/numpy/numpy_ufunc.asp También ejecutan una operación elemento a elemento sobre un arreglo Reemplazan los operadores individuales. Son funciones nativas

Ejemplos:
<ul><li>np.add(vector,4) # suma 4</li>
<li>np.substract(vector,2) # resta 2</li>
<li>np.multiply</li>
<li>np.floor_divide(vector,3) # devuelve la division entera</li>
<li>np.negative(vector)</li>
<li>np.power(vector,2) #potencia</li>
<li>np.mod(vector,2)</li></ul>

In [23]:
vector = np.array([(8, 9, 10), (11, 12, 13)])

print(vector.min())  # me devuelve el elemento MENOR de la matriz
print(vector.max())  # me devuelve el elemento MAYOR de la matriz
print(vector.sum())  # me devuelve la suma detodo los elementos de la matriz

print(np.sqrt(vector))  # me devuelve la raiz cuadrada de c/u de los valores del vector
print(np.negative(vector))  # me transforma todos los valores en negativo
# tanto 'np.sqrt(vector)' como 'n'p.negative(vector)' NO ALTERA la matriz original
# estan retornando una copia alterada
# si deseamos almacenarla debemos hacerlo en otra variable

print(np.power(vector, 2)) # me devuelve la potencia de c/u de los valores del vector


8
13
63
[[2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128]]
[[ -8  -9 -10]
 [-11 -12 -13]]
[[ 64  81 100]
 [121 144 169]]


In [24]:
#from scipy import stats
#SciPy es un biblioteca de algoritmos matemáticos


<h3>Método append</h3>
Para agregar filas o columnas

In [25]:
print("Arreglo original")
mi_array = np.array(([1,4,19,10,5],[3,9,10,8,8]))
print(mi_array)



Arreglo original
[[ 1  4 19 10  5]
 [ 3  9 10  8  8]]


In [26]:
# MÉTODO APPEND: ARRAY ORIGINAL +  2 FILAS EXTRA

print("Array con dos filas extra")
mi_array_2 = np.append(mi_array, ([0,0,0,0,0] , [1,1,1,1,1]), axis=0)
print(mi_array_2)

# AXIS=0 ES EL EJE 'X'

# ESTO ES UNA COPIA ALTERADA DE MI ARREGLO CON + 2 FILAS

Array con dos filas extra
[[ 1  4 19 10  5]
 [ 3  9 10  8  8]
 [ 0  0  0  0  0]
 [ 1  1  1  1  1]]


In [27]:
# MÉTODO APPEND: ARRAY ORIGINAL + 5 COLUMNAS EXTRA

print("Array con dos filas extra")
mi_array_3 = np.append(mi_array, ([0,0,0,0,0] , [1,1,1,1,1]), axis=1)
print(mi_array_3)

# AXIS=1 ES EL EJE 'Y'

# ESTO ES UNA COPIA ALTERADA DE MI ARREGLO CON + 2 COLUMNAS

Array con dos filas extra
[[ 1  4 19 10  5  0  0  0  0  0]
 [ 3  9 10  8  8  1  1  1  1  1]]


<h3>Repaso de acceso a los elementos y slicing</h3>
Para obtener fragmentos de nuestros sets de datos.

In [28]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
print(a)


[[ 1  0  3]
 [ 4  3  5]
 [ 6 10 -1]]


In [29]:
# Quiero acceder al 10 (recuerdo que las posiciones empiezan a contarse desde 0)

print(a[2,1])

# De esta manera accedemos a un elemento determinado
# print(array[row,column])

10


In [30]:
# recordemos que si estamos en un array de una sola dimensión, ponemos únicamente 
# el índice que corresponde al elemento que buscamos y listo!
a2 = np.array([25, 36, 10, 85, 56])

print(a2)

print(a2[3])

#tambien podemos indicar print(a2[-2])

[25 36 10 85 56]
85


In [31]:
# SLICING TOTAL -> Para obtener todos los elementos
a2 = np.array([25, 36, 10, 85, 56])
print(a)

print(a[:]) # nos devuelve todos los valores

print(a2[1:3])

# en el slicing NO se incluye el punto final de corte
# en este caso no incluiria el 3.

[[ 1  0  3]
 [ 4  3  5]
 [ 6 10 -1]]
[[ 1  0  3]
 [ 4  3  5]
 [ 6 10 -1]]
[36 10]


Puedo usar RANGOS de búsqueda, usando el mismo formato <code><mark>inicio:tope:paso</mark></code> de range.
Supongamos que quiero obtener los datos de las celdas:
<ul><li>naranja</li>
<li>turquesa</li>
<li>rojo</li>
<li>verde</li></ul>
<center><img src='img/slicing.png'></center>

In [32]:
# CREO LA MATRIZ

matriz = np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
print(matriz)



[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [33]:
# BUSCO EL RANGO EN NARANJA

# Fila 0 - Columnas 3 y 4 (la 5 no entra porque es el tope)
print(matriz[0, 3:5])



[3 4]


In [34]:
# BUSCO EL RANGO TURQUESA

# Fila 4 y 5 - Columna 4 y 5
print(matriz[4: , 4:])


[[44 45]
 [54 55]]


In [35]:
# BUSCO EL RANGO ROJO

# Todas las filas - Columna 2
print(matriz[: , 2])


[ 2 12 22 32 42 52]


In [36]:
# Si quiero que se imprima en columna, recuerdo que tengo el método reshape(filas,columnas)

# Todas las filas - Columna 2 (con reshape)
print(matriz[: , 2].reshape(6,1))
# utilizamos reshape para viasualizarlo como columna a los valores

[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]


In [37]:
# BUSCO EL RANGO VERDE

# Filas 2 y 4 - Columnas 0, 2 y 4 (con step)
print(matriz[2::2 , ::2])

# matriz[inicio:fin:salto , :]  en este caso lo aplicamos en filas
#cuando indicamos ::2 hacemos referencia los saltos entre valores 
#en este caso son saltos de a dos 


[[20 22 24]
 [40 42 44]]


<h3>Boolean Masking</h3>
Puedo obtener información sobre el contenido de mi arreglo, como valores repetidos, por encima o debajo de cierto valor, etc.

Podemos hacerlo mediante operadores mediante o ufuncs

In [38]:
# CREO UNA MATRIZ CON VALORES ALEATORIOS, pero no quiero que cambien los valores cada vez que ejecuto mi código

np.random.seed(0)
arr_aleatorio = np.random.randint(0,100,(20,20))
print(arr_aleatorio)
 
# En este caso creamos un arreglo de 20x20 con num aleatorios entre 0 y 100
# np.random.seed nos permite que los num aleatorios sean siempre los mismos
# Cada vez que corremos nos dara siempre el mismo set aleatorio, NO SE ALTERA

[[44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
 [81 37 25 77 72  9 20 80 69 79 47 64 82 99 88 49 29 19 19 14]
 [39 32 65  9 57 32 31 74 23 35 75 55 28 34  0  0 36 53  5 38]
 [17 79  4 42 58 31  1 65 41 57 35 11 46 82 91  0 14 99 53 12]
 [42 84 75 68  6 68 47  3 76 52 78 15 20 99 58 23 79 13 85 48]
 [49 69 41 35 64 95 69 94  0 50 36 34 48 93  3 98 42 77 21 73]
 [ 0 10 43 58 23 59  2 98 62 35 94 67 82 46 99 20 81 50 27 14]
 [41 58 65 36 10 86 43 11  2 51 80 32 54  0 38 19 46 42 56 60]
 [77 30 24  2  3 94 98 13 40 72 19 95 72 26 66 52 67 61 14 96]
 [ 4 67 11 86 77 75 56 16 24 29 21 25 80 60 61 83 33 32 70 85]
 [31 13 71 56 24 79 41 18 40 54 79 11 38 93  1 95 44 88 24 67]
 [82  3 76 35 86 61 69 87 43 32 11 84 10 54 37 28  2 27 83 89]
 [23 53 51 46 20 53 29 67 35 39  9 73 41 23  3 46 90 50  3 31]
 [ 9 10 27 45 71 39 61 85 97 44 34 34 88 33  5 36  0 75 34 69]
 [53 80 62  8 61  1 81 35 91 40 36 48 25 67 35 30 29 33 18 17]
 [93 84  2 69 12 44 66 91 85 39 39 75 22 30 17 70 71 18

In [39]:
# Uso operadores para buscar

print("True donde el numero es < 50 ")
print( arr_aleatorio < 50)


True donde el numero es < 50 
[[ True  True False False False  True False  True  True False False False
  False  True False False  True False  True False]
 [False  True  True False False  True  True False False False  True False
  False False False  True  True  True  True  True]
 [ True  True False  True False  True  True False  True  True False False
   True  True  True  True  True False  True  True]
 [ True False  True  True False  True  True False  True False  True  True
   True False False  True  True False False  True]
 [ True False False False  True False  True  True False False False  True
   True False False  True False  True False  True]
 [ True False  True  True False False False False  True False  True  True
   True False  True False  True False  True False]
 [ True  True  True False  True False  True False False  True False False
  False  True False  True False False  True  True]
 [ True False False  True  True False  True  True  True False False  True
  False  True  True  

In [40]:
# numeros True dentro del arreglo
print(arr_aleatorio == 44)
print(arr_aleatorio == 67)

[[ True False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]


In [41]:
# Con Ufuncs

# np.equal(array, valor)
# comprueba cada uno de los elementos si son iguales al valor - en este caso '30'

print(np.equal(arr_aleatorio, 30))


[[False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]


In [42]:
#Con Ufuncs

# np.less(array, valor)
# comprueba si es mayor cada uno de los elementos a el valor - en este caso '32'
print(np.less(arr_aleatorio, 32))


[[False False False False False  True False  True False False False False
  False  True False False False False False False]
 [False False  True False False  True  True False False False False False
  False False False False  True  True  True  True]
 [False False False  True False False  True False  True False False False
   True False  True  True False False  True False]
 [ True False  True False False  True  True False False False False  True
  False False False  True  True False False  True]
 [False False False False  True False False  True False False False  True
   True False False  True False  True False False]
 [False False False False False False False False  True False False False
  False False  True False False False  True False]
 [ True  True False False  True False  True False False False False False
  False False False  True False False  True  True]
 [False False False False  True False False  True  True False False False
  False  True False  True False False False False]


In [43]:
# Contando valores especificos en toda la matriz
# Cuenta todos los elementos que no son igual al valor - en este caso dif a '0' 
print(np.count_nonzero(arr_aleatorio))

# Contando valores específicos por fila, agregando la opción axis
print(np.sum(arr_aleatorio < 50 , axis=1)) 
# En este caso indica la suma de todos los valores MENORES a 50, en cada columna
# axis = 1 indica que realizamos la suma (de la condicion) en cada una de las columnas

391
[ 8 10 14 12  9 10 10 12  9  9 11 10 13 13 13 10  8  5 12 10]


<h3>Método copy</h3>
Permite crear copias de arrays.

In [44]:
mi_array4 = np.array(([1,4,19,10,5],[3,9,10,8,8]))


# con el ID podemos observar que las dos variables referencian al mismo arreglo
# ambos apuntas a la misma direccion de memoria
mi_array5 = mi_array4

print(id(mi_array4))
print(id(mi_array5))


# En este caso podemos observarque el ID de ambas variables referencian diferentes arreglos
# ambos apuntan a diferentes direccion de memoria
mi_array6 = np.copy(mi_array4)

print(id(mi_array4))
print(id(mi_array6))

139952753624528
139952753624528
139952753624528
139952753624240


<h3>Arreglos de Booleanos</h3>
Con dtype puedo cambiar cómo se muestran los valores en pantalla

In [45]:
booleanos1 = np.array([1,0,1,1,0,1,0,0])
booleanos2 = np.array([1,0,1,1,0,1,0,0], dtype=bool)

print( booleanos1 )
print( booleanos2 )

[1 0 1 1 0 1 0 0]
[ True False  True  True False  True False False]


In [46]:
booleanos1 = np.array([1,0,1,1,0,1,0,0])
booleanos3 = np.array([0,0,1,0,1,1,0,1])

booleanos4 = booleanos1 & booleanos3  # AND
print("And:" , booleanos4)

booleanos5 = booleanos1 | booleanos3 # OR
print("OR:" , booleanos5)


# Para poder aplicar '&' (and) , '|' (or) los arreglos debe ser del mismo tipo
# Se representan como booleanos, el 1 es Verdadero y el 0 es Falso
# Obtenemos es resultado de una CONJUNCION (and - &) o de una DISYUNCION (or - |)

And: [0 0 1 0 0 1 0 0]
OR: [1 0 1 1 1 1 0 1]


In [47]:
# Aplicando ufuncs obtengo los valores True y False

booleanos6 = np.logical_and(booleanos1 , booleanos3)
booleanos7 = np.logical_or(booleanos1 , booleanos3)

print("And:" , booleanos6 )

# otra manera de obtener valores booleanos con funciones nativas


And: [False False  True False False  True False False]


<h3>all() y any()</h3>
Métodos para evaluar todos los valores de un arreglo

In [48]:
# 'ALL' me permite evaluar si todos los valores son True
# 'ANY' me permite evaluar si hay algún valor True

booleanos1 = np.array([1,0,1,1,0,1,0,0])
booleanos8 = np.array([0,0,0,0,0,0,0,0])
booleanos9 = np.array([1,1,1,1,1,1,1,1])

print("Todos los valores del arreglo son True")
print(np.all(booleanos1))
print(np.all(booleanos8))
print(np.all(booleanos9))

print()

print("Algun valor del arreglo es True")
print(np.any(booleanos1))
print(np.any(booleanos8))
print(np.any(booleanos9))


Todos los valores del arreglo son True
False
False
True

Algun valor del arreglo es True
True
False
True


<h3>Broadcasting</h3>
NumPy me permite operar entre arreglos de diferente estructura, transformándolos para que tengan el mismo tamaño para que no se generen errores.

Así es el proceso:
<center><img src='img/broadcasting.png'></center>

In [49]:

vector_a = np.arange(0, 20, 5)  #np.arange(min, max, saltos)
print(vector_a)

[ 0  5 10 15]


In [50]:
print(vector_a.shape)  #.shape nos permite ver la forma de nuestro arregloctor 

(4,)


In [51]:
# 'np.newaxis' es un metodo nos permite cambiar la orientacion de nuestro arreglo

vector_b = vector_a[:, np.newaxis]
print(vector_b)
print(vector_a.shape)

# nuestro arreglo paso de tener 1 fila y 4 columnas a tener 4 columnas y 1 fila

print(id(vector_a))
print(id(vector_b))
# tienen diferente direccion de memoria

[[ 0]
 [ 5]
 [10]
 [15]]
(4,)
139952754361520
139952754067856


In [52]:
print( vector_a + vector_b )

# completo la fila, completo la columna y sumo a cada uno.

[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]


<h4>Actividades</h4>
1. Crear un vector3 de 1 fila y 6 columnas con los datos 5,10,15,20,25,30
   Crear un vector4 de 5 filas y 1 columna con los datos 100,200,300,400,500
   (Crédito extra para quien use arange + newaxis para crear los vectores)
   Crear el vector5, a partir de vector4 - vector3

2. Usando slicing, obtener de vector5 los siguientes datos y cargarlos en vector6,vector7,vector8:

In [ ]:
'''
a. [[ 285 280 275 ]
    [ 385 380 375 ]]

b. [ 290 280 270 ]

c. [[  75 ]
    [ 275 ]
    [ 475 ]]
'''

'\na. [[ 285 280 275 ]\n    [ 385 380 375 ]]\n\nb. [ 290 280 270 ]\n\nc. [[  75 ]\n    [ 275 ]\n    [ 475 ]]\n'

In [53]:
vector3 = np.arange(5, 31, 5)
print(vector3)

print(vector3.shape)

[ 5 10 15 20 25 30]
(6,)


In [54]:
vector2 = np.arange(100, 501, 100)
print(vector2)

print(vector2.shape)

[100 200 300 400 500]
(5,)


In [55]:
vector4 = vector2[:, np.newaxis]
print(vector4)

# 'np.newaxis' nos cambia de eje nuestro arreglo

[[100]
 [200]
 [300]
 [400]
 [500]]


In [66]:
# Otra manera de crear el arreglo de una manera más 'básica' es con array:
# creando una lista de cinco elementos
# en el caso de vector 4 tambien aplicamos reshape - modificamos row, column

# vector3:
vector_3 = np.array([5, 10, 15, 20, 25, 30])
print(vector_3)

# vector4:
vector_4 = np.array([100, 200, 300, 400, 500])
vector_4 = vector_4.reshape(5,1)
print(vector_4)

[ 5 10 15 20 25 30]
[[100]
 [200]
 [300]
 [400]
 [500]]


In [56]:
# resta entre vectores
vector5=(vector4 - vector3)
print(vector5)

[[ 95  90  85  80  75  70]
 [195 190 185 180 175 170]
 [295 290 285 280 275 270]
 [395 390 385 380 375 370]
 [495 490 485 480 475 470]]


In [75]:
# SLICING , debemos obtener los datos:

'''
a. [[ 285 280 275 ]
    [ 385 380 375 ]]

b. [ 290 280 270 ]

c. [[  75 ]
    [ 275 ]
    [ 475 ]]
'''

# a.

vector6 = vector5[2:4 , 2:5]
print(vector6)

print()

# b.

vector7 = vector5[2 , 1::2]
print(vector7)

print()

#c.

vector8 = vector5[::2 , 4:5]
print(vector8)

# otra manera de realizarlo (c.) :
#  vector8 = vector8[::2 , 4, np.newaxis]

[[285 280 275]
 [385 380 375]]

[290 280 270]

[[ 75]
 [275]
 [475]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=d0115063-a8da-423e-9757-b15a7758d9e5' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>